const skills = [
  {
    id: 1,
    name: "Turn Base Game",
    imageSource: "img/turnbase.png",
    alt: "Turn base JavaScript game",
    body: "Turn base game is a two player take turn game. Players can pick and swap weapons, choose to either attack or defend whenever either of the players move into an adjacent square that is not more than 3 squares away from the other player.",
    github: "https://github.com/samspecial",
    deployedLink: "https://samuelosinloye.io/turnbase-game",
  },
  {
    id: 2,
    name: "Restaurant Review",
    imageSource: "img/restaurant.png",
    alt: "Restaurant Review website with Geolocation",
    body: "Restaurant Review Geolocation based Web App is built using ReactJS and the browser navigator API to retreive Restaurant within 300km radius of the user location using the Google Maps API.",
    github: "https://github.com/samspecial/restaurant-review",
    deployedLink: "https://restaurant-review.vercel.app/",
  },
  {
    id: 3,
    name: "Fast Learn",
    imageSource: "img/fastlearn.png",
    alt: "Fast Learn eLearning Platform",
    body: "Fast Learn WebApp is a distance-learning platform for attracting thousands of students from various countries. The website is developed for three different types of users: Students, Instructors, and Administrators with each provided with a user name and password to log on to the site.",
    github: "https://github.com/samspecial/fastlearn",
    deployedLink: "https://fastlearnapp.azurewebsites.net/",
  },
  {
    id: 4,
    name: "Loan App",
    imageSource: "img/Loan-application.png",
    alt: "Loan Application App",
    body: "Loan Calculator is a JavaScript Application with a rich user interface which helps both new and existing loan applicants to estimate the cost incurred to service the loan on a monthly basis based on the number of months the applicants believe would be convenient on his/her part to payback.",
    github: "https://github.com/samspecial/loan-estimator/",
    deployedLink: "http://samuelosinloye.me/loan-estimator/",
  },
  {
    id: 5,
    name: "TeamWork",
    imageSource: "img/teamwork.png",
    alt: "Teamwork Social Application",
    body: "Teamwork is a Social Networing Application for employees within an organization to share and post image content with various categories such as politics, sports, education, news, entertainment, business etc. The adminstrator of each company is saddled with the responsibility of onboarding new users.",
    github: "https://github.com/samspecial/teamworkapp",
    deployedLink: "http://teamwork-social-app.herokuapp.com/",
  },
  {
    id: 6,
    name: "Samspecial Blog",
    imageSource: "img/samspecial.png",
    alt: "Samspecial Blog App",
    body: "Samspecial Blog App is built using ASP.NET Core MVC. Readers are served with latest news and stories of the hour from various parts of the world across different categories such as Sports, Entertainment, Music, Politics, Education, Business, Career etc",
    github: "https://github.com/samspecial/",
    deployedLink: "https://samspecialblog.azurewebsites.net/",
  },
];
